nose.plugins.cover: ERROR: Coverage not available: unable to import coverage module
Traceback (most recent call last):
  File "scripts/ci/run-tests", line 19, in <module>
    run('nosetests --with-coverage --cover-erase --cover-package ibm_botocore '
  File "scripts/ci/run-tests", line 16, in run
    return check_call(command, shell=True)
  File "/root/.pyenv/versions/2.7.8/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/root/.pyenv/versions/2.7.8/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/root/.pyenv/versions/2.7.8/lib/python2.7/subprocess.py", line 1376, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/root/.pyenv/versions/2.7.8/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
Traceback (most recent call last):
  File "/root/.pyenv/versions/2.7.8/bin/nosetests", line 11, in <module>
    sys.exit(run_exit())
  File "/root/.pyenv/versions/2.7.8/lib/python2.7/site-packages/nose/core.py", line 121, in __init__
    **extra_args)
  File "/root/.pyenv/versions/2.7.8/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/root/.pyenv/versions/2.7.8/lib/python2.7/site-packages/nose/core.py", line 179, in parseArgs
    self.createTests()
  File "/root/.pyenv/versions/2.7.8/lib/python2.7/site-packages/nose/core.py", line 193, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames)
  File "/root/.pyenv/versions/2.7.8/lib/python2.7/site-packages/nose/loader.py", line 481, in loadTestsFromNames
    return unittest.TestLoader.loadTestsFromNames(self, names, module)
  File "/root/.pyenv/versions/2.7.8/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/root/.pyenv/versions/2.7.8/lib/python2.7/site-packages/nose/loader.py", line 433, in loadTestsFromName
    discovered=discovered)
  File "/root/.pyenv/versions/2.7.8/lib/python2.7/site-packages/nose/loader.py", line 354, in loadTestsFromModule
    tests.extend(self.loadTestsFromDir(module_path))
  File "/root/.pyenv/versions/2.7.8/lib/python2.7/site-packages/nose/loader.py", line 183, in loadTestsFromDir
    entry_path, discovered=True)
  File "/root/.pyenv/versions/2.7.8/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/root/.pyenv/versions/2.7.8/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/root/.pyenv/versions/2.7.8/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/git/cleversafe/sdk/python/ibm-cos-sdk-python-core/tests/functional/test_waiter_config.py", line 14, in <module>
    from jsonschema import Draft4Validator
  File "/root/.pyenv/versions/2.7.8/lib/python2.7/site-packages/jsonschema/__init__.py", line 12, in <module>
    from jsonschema.exceptions import (
  File "/root/.pyenv/versions/2.7.8/lib/python2.7/site-packages/jsonschema/exceptions.py", line 6, in <module>
    from jsonschema import _utils
  File "/root/.pyenv/versions/2.7.8/lib/python2.7/site-packages/jsonschema/_utils.py", line 6, in <module>
    from jsonschema.compat import str_types, MutableMapping, urlsplit
  File "/root/.pyenv/versions/2.7.8/lib/python2.7/site-packages/jsonschema/compat.py", line 1, in <module>
    import operator
KeyboardInterrupt
